In [16]:
import pandas as pd
import numpy as np
# import seaborn as sns

In [17]:
df_Game_players = pd.read_csv('../data/raw/games_by_players.csv').copy()
df_Game_team = pd.read_csv('../data/raw/games_by_teams.csv').copy()
df_main = pd.read_csv('../data/raw/main.csv').copy()
df_match_players = pd.read_csv('../data/raw/matches_by_players.csv').copy()
df_match_team = pd.read_csv('../data/raw/matches_by_teams.csv').copy()
df_players = pd.read_csv('../data/raw/players_db.csv').copy()

C:\Users\attis\AppData\Local\Temp\ipykernel_21304\3747949340.py:1: DtypeWarning: Columns (92) have mixed types. Specify dtype option on import or set low_memory=False.
  df_Game_players = pd.read_csv('../data/raw/games_by_players.csv').copy()

In [18]:
df_Game_players.info()
df_Game_players.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106795 entries, 0 to 106794
Columns: 103 entries, game_id to camera_transition_speed
dtypes: bool(2), float64(87), int64(5), object(9)
memory usage: 82.5+ MB

,game_id,color,team_id,team_region,player_id,player_tag,core_shots,core_goals,core_saves,core_assists,...,car_id,car_name,steering_sensitivity,camera_fov,camera_height,camera_pitch,camera_distance,camera_stiffness,camera_swivel_speed,camera_transition_speed
0,616004f3143c37878b238690,blue,6020bc8ef1e4807cc700391a,Oceania,5f3d8fdd95f40596eae2412e,Amphis,4,1,1,0,...,4284.0,Fennec,3.05,110.0,100.0,-3.0,260.0,0.40,2.4,1.2
1,616004f3143c37878b238690,blue,6020bc8ef1e4807cc700391a,Oceania,5f3d8fdd95f40596eae23e01,Torsos,5,0,2,1,...,403.0,Dominus,1.00,110.0,100.0,-2.0,250.0,0.55,10.0,1.4
2,616004f3143c37878b238690,blue,6020bc8ef1e4807cc700391a,Oceania,5f3d8fdd95f40596eae23e53,Express,4,1,0,0,...,4284.0,Fennec,1.30,110.0,100.0,-3.0,260.0,0.50,2.5,1.2
3,616004f3143c37878b238690,orange,614c8930f8090ec745286474,Oceania,604e562901d675f81a96b270,mel kin,2,0,6,0,...,403.0,Dominus,1.51,110.0,90.0,-4.0,280.0,0.30,6.0,1.0
4,616004f3143c37878b238690,orange,614c8930f8090ec745286474,Oceania,5f7ca648ea8a0f0714fb9a20,Laxin,1,0,3,0,...,23.0,Octane,1.75,110.0,90.0,-5.0,270.0,0.25,10.0,1.0
5,616004f3143c37878b238690,orange,614c8930f8090ec745286474,Oceania,5f3d8fdd95f40596eae24503,Baked Potato,1,1,1,0,...,4284.0,Fennec,2.00,110.0,90.0,-5.0,270.0,0.35,8.0,1.4
6,616004f7143c37878b238697,blue,6020bc8ef1e4807cc700391a,Oceania,5f3d8fdd95f40596eae2412e,Amphis,4,2,1,0,...,4284.0,Fennec,3.05,110.0,100.0,-3.0,260.0,0.40,2.4,1.2
7,616004f7143c37878b238697,blue,6020bc8ef1e4807cc700391a,Oceania,5f3d8fdd95f40596eae23e01,Torsos,2,1,0,2,...,403.0,Dominus,1.00,110.0,100.0,-2.0,250.0,0.55,10.0,1.4
8,616004f7143c37878b238697,blue,6020bc8ef1e4807cc700391a,Oceania,5f3d8fdd95f40596eae23e53,Express,4,1,2,1,...,4284.0,Fennec,1.30,110.0,100.0,-3.0,260.0,0.50,2.5,1.2
9,616004f7143c37878b238697,orange,614c8930f8090ec745286474,Oceania,5f3d8fdd95f40596eae24503,Baked Potato,2,2,2,0,...,4284.0,Fennec,2.00,110.0,90.0,-5.0,270.0,0.35,8.0,1.4

In [19]:
df_Game_team.info()
df_Game_team.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35594 entries, 0 to 35593
Data columns (total 55 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   game_id                             35594 non-null  object
 1   color                               35594 non-null  object
 2   team_id                             35594 non-null  object
 3   team_slug                           35594 non-null  object
 4   team_name                           35594 non-null  object
 5   team_region                         35555 non-null  object
 6   ball_possession_time                34998 non-null  float64
 7   ball_time_in_side                   34998 non-null  float64
 8   core_shots                          35594 non-null  int64
 9   core_goals                          35594 non-null  int64
 10  core_saves                          35594 non-null  int64
 11  core_assists                        35594 non-null  int64
 12  core_score                          35594 non-null  int64
 13  core_shooting_percentage            35594 non-null  float64
 14  boost_bpm                           35224 non-null  float64
 15  boost_bcpm                          35224 non-null  float64
 16  boost_avg_amount                    35224 non-null  float64
 17  boost_amount_collected              35224 non-null  float64
 18  boost_amount_stolen                 35224 non-null  float64
 19  boost_amount_collected_big          35224 non-null  float64
 20  boost_amount_stolen_big             35224 non-null  float64
 21  boost_amount_collected_small        35224 non-null  float64
 22  boost_amount_stolen_small           35224 non-null  float64
 23  boost_count_collected_big           35224 non-null  float64
 24  boost_count_stolen_big              35224 non-null  float64
 25  boost_count_collected_small         35224 non-null  float64
 26  boost_count_stolen_small            35224 non-null  float64
 27  boost_amount_overfill               35224 non-null  float64
 28  boost_amount_overfill_stolen        35224 non-null  float64
 29  boost_amount_used_while_supersonic  35224 non-null  float64
 30  boost_time_zero_boost               35224 non-null  float64
 31  boost_time_full_boost               35224 non-null  float64
 32  boost_time_boost_0_25               35224 non-null  float64
 33  boost_time_boost_25_50              35224 non-null  float64
 34  boost_time_boost_50_75              35224 non-null  float64
 35  boost_time_boost_75_100             35224 non-null  float64
 36  movement_total_distance             35224 non-null  float64
 37  movement_time_supersonic_speed      35224 non-null  float64
 38  movement_time_boost_speed           35224 non-null  float64
 39  movement_time_slow_speed            35224 non-null  float64
 40  movement_time_ground                35224 non-null  float64
 41  movement_time_low_air               35224 non-null  float64
 42  movement_time_high_air              35224 non-null  float64
 43  movement_time_powerslide            35224 non-null  float64
 44  movement_count_powerslide           35224 non-null  float64
 45  positioning_time_defensive_third    35224 non-null  float64
 46  positioning_time_neutral_third      35224 non-null  float64
 47  positioning_time_offensive_third    35224 non-null  float64
 48  positioning_time_defensive_half     35224 non-null  float64
 49  positioning_time_offensive_half     35224 non-null  float64
 50  positioning_time_behind_ball        35224 non-null  float64
 51  positioning_time_in_front_ball      35224 non-null  float64
 52  demo_inflicted                      35224 non-null  float64
 53  demo_taken                          35224 non-null  float64
 54  winner                              35594 non-null  bool
dtypes: bool(1), float64(43), int64(5), object(6)
memory usage: 14.7+ MB

,game_id,color,team_id,team_slug,team_name,team_region,ball_possession_time,ball_time_in_side,core_shots,core_goals,...,positioning_time_defensive_third,positioning_time_neutral_third,positioning_time_offensive_third,positioning_time_defensive_half,positioning_time_offensive_half,positioning_time_behind_ball,positioning_time_in_front_ball,demo_inflicted,demo_taken,winner
0,616004f3143c37878b238690,blue,6020bc8ef1e4807cc700391a,https://octane.gg/teams/391a-ground-zero-gaming,GROUND ZERO GAMING,Oceania,136.54,170.84,13,2,...,513.73,291.06,189.48,660.06,334.20,727.07,267.20,1.0,3.0,True
1,616004f3143c37878b238690,orange,614c8930f8090ec745286474,https://octane.gg/teams/6474-ranga-roundup,RANGA ROUNDUP,Oceania,153.60,148.51,4,1,...,457.04,329.25,214.03,633.39,366.93,740.69,259.64,3.0,1.0,False
2,616004f7143c37878b238697,blue,6020bc8ef1e4807cc700391a,https://octane.gg/teams/391a-ground-zero-gaming,GROUND ZERO GAMING,Oceania,155.79,145.60,10,4,...,507.95,308.51,264.92,659.74,421.65,780.01,301.38,5.0,1.0,True
3,616004f7143c37878b238697,orange,614c8930f8090ec745286474,https://octane.gg/teams/6474-ranga-roundup,RANGA ROUNDUP,Oceania,126.81,185.78,6,2,...,561.51,360.96,147.48,762.21,307.73,782.32,287.61,1.0,5.0,False
4,616004fc143c37878b23869e,blue,6020bc8ef1e4807cc700391a,https://octane.gg/teams/391a-ground-zero-gaming,GROUND ZERO GAMING,Oceania,165.76,136.11,11,3,...,476.66,373.66,279.05,648.19,481.20,832.70,296.69,0.0,3.0,True
5,616004fc143c37878b23869e,orange,614c8930f8090ec745286474,https://octane.gg/teams/6474-ranga-roundup,RANGA ROUNDUP,Oceania,141.17,218.16,5,2,...,602.53,370.50,165.27,813.96,324.33,795.25,343.05,3.0,0.0,False
6,61614e40f8090ec74528706b,blue,6020bc70f1e4807cc70023fb,https://octane.gg/teams/23fb-renegades,RENEGADES,Oceania,140.93,105.92,14,8,...,395.84,406.49,330.77,600.69,532.35,881.32,251.78,3.0,2.0,True
7,61614e40f8090ec74528706b,orange,6156d4db143c37878b238367,https://octane.gg/teams/8367-trident-esports,TRIDENT ESPORTS,Oceania,126.65,233.63,3,0,...,745.55,286.20,98.08,916.82,213.00,747.43,382.40,2.0,3.0,False
8,61614e45143c37878b2387b8,blue,6020bc70f1e4807cc70023fb,https://octane.gg/teams/23fb-renegades,RENEGADES,Oceania,142.42,112.64,14,6,...,405.76,455.42,326.10,627.00,560.28,896.19,291.09,5.0,3.0,True
9,61614e45143c37878b2387b8,orange,6156d4db143c37878b238367,https://octane.gg/teams/8367-trident-esports,TRIDENT ESPORTS,Oceania,151.10,246.07,5,2,...,691.43,346.17,140.91,883.18,295.33,801.17,377.34,3.0,5.0,False

In [20]:
df_main.info()
df_main.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18740 entries, 0 to 18739
Data columns (total 36 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   event_id               18740 non-null  object
 1   event                  18740 non-null  object
 2   event_split            18740 non-null  object
 3   event_region           18740 non-null  object
 4   event_slug             18740 non-null  object
 5   event_start_date       18740 non-null  object
 6   event_end_date         18740 non-null  object
 7   event_tier             18740 non-null  object
 8   event_phase            18740 non-null  object
 9   prize_money            18740 non-null  float64
 10  stage_step             18740 non-null  int64
 11  stage                  18740 non-null  object
 12  stage_start_date       18740 non-null  object
 13  stage_end_date         18740 non-null  object
 14  stage_is_lan           18740 non-null  bool
 15  stage_is_qualifier     18740 non-null  bool
 16  liquipedia_link        18740 non-null  object
 17  location_venue         789 non-null    object
 18  location_city          789 non-null    object
 19  location_country       789 non-null    object
 20  match_id               18740 non-null  object
 21  match_slug             18740 non-null  object
 22  match_number           18740 non-null  int64
 23  match_round            18740 non-null  object
 24  match_date             18740 non-null  object
 25  match_format           18740 non-null  object
 26  reverse_sweep_attempt  18740 non-null  bool
 27  reverse_sweep          18740 non-null  bool
 28  game_id                17797 non-null  object
 29  game_number            17797 non-null  float64
 30  game_date              17612 non-null  object
 31  game_duration          17797 non-null  float64
 32  map_id                 17715 non-null  object
 33  map_name               17715 non-null  object
 34  overtime               17797 non-null  object
 35  ballchasing_id         17612 non-null  object
dtypes: bool(4), float64(3), int64(2), object(27)
memory usage: 4.6+ MB

,event_id,event,event_split,event_region,event_slug,event_start_date,event_end_date,event_tier,event_phase,prize_money,...,reverse_sweep_attempt,reverse_sweep,game_id,game_number,game_date,game_duration,map_id,map_name,overtime,ballchasing_id
0,614b7046f8090ec74528642d,Regional 1,Fall,Oceania,https://octane.gg/events/642d-rlcs-2021-22-fal...,2021-10-07 23:00:00+00:00,2021-10-17 22:30:00+00:00,Qualifier,Invitational Qualifier,0.0,...,False,False,616004f3143c37878b238690,1.0,2021-10-08 06:08:23+00:00,300.0,stadium_p,DFH Stadium,False,15f12bd9-f4a6-4cea-a2dc-610cd9dd976b
1,614b7046f8090ec74528642d,Regional 1,Fall,Oceania,https://octane.gg/events/642d-rlcs-2021-22-fal...,2021-10-07 23:00:00+00:00,2021-10-17 22:30:00+00:00,Qualifier,Invitational Qualifier,0.0,...,False,False,616004f7143c37878b238697,2.0,2021-10-08 06:16:09+00:00,300.0,stadium_p,DFH Stadium,False,2f01deab-3f2f-412f-a70e-72b39b3b204a
2,614b7046f8090ec74528642d,Regional 1,Fall,Oceania,https://octane.gg/events/642d-rlcs-2021-22-fal...,2021-10-07 23:00:00+00:00,2021-10-17 22:30:00+00:00,Qualifier,Invitational Qualifier,0.0,...,False,False,616004fc143c37878b23869e,3.0,2021-10-08 06:23:31+00:00,326.0,stadium_p,DFH Stadium,True,3b0fc17c-6f8d-4e94-a625-e0fa988d7cc0
3,614b7046f8090ec74528642d,Regional 1,Fall,Oceania,https://octane.gg/events/642d-rlcs-2021-22-fal...,2021-10-07 23:00:00+00:00,2021-10-17 22:30:00+00:00,Qualifier,Invitational Qualifier,0.0,...,False,False,61614e40f8090ec74528706b,1.0,2021-10-08 06:10:54+00:00,300.0,stadium_p,DFH Stadium,False,6e5e523a-3299-42d1-8b34-7ac0baa1b771
4,614b7046f8090ec74528642d,Regional 1,Fall,Oceania,https://octane.gg/events/642d-rlcs-2021-22-fal...,2021-10-07 23:00:00+00:00,2021-10-17 22:30:00+00:00,Qualifier,Invitational Qualifier,0.0,...,False,False,61614e45143c37878b2387b8,2.0,2021-10-08 06:18:58+00:00,300.0,stadium_p,DFH Stadium,False,95bfed45-3271-407b-9188-a278dfa8f66e
5,614b7046f8090ec74528642d,Regional 1,Fall,Oceania,https://octane.gg/events/642d-rlcs-2021-22-fal...,2021-10-07 23:00:00+00:00,2021-10-17 22:30:00+00:00,Qualifier,Invitational Qualifier,0.0,...,False,False,61614e4a143c37878b2387bf,3.0,2021-10-08 06:26:28+00:00,300.0,stadium_p,DFH Stadium,False,fc03d314-c17f-4d50-a3b7-f2da81b2dba3
6,614b7046f8090ec74528642d,Regional 1,Fall,Oceania,https://octane.gg/events/642d-rlcs-2021-22-fal...,2021-10-07 23:00:00+00:00,2021-10-17 22:30:00+00:00,Qualifier,Invitational Qualifier,0.0,...,False,False,616150a6f8090ec74528710c,1.0,2021-10-08 06:06:28+00:00,300.0,stadium_p,DFH Stadium,False,c742de92-3625-46f7-80e1-b5686d50a4ec
7,614b7046f8090ec74528642d,Regional 1,Fall,Oceania,https://octane.gg/events/642d-rlcs-2021-22-fal...,2021-10-07 23:00:00+00:00,2021-10-17 22:30:00+00:00,Qualifier,Invitational Qualifier,0.0,...,False,False,616150aa143c37878b238860,2.0,2021-10-08 06:14:06+00:00,300.0,stadium_p,DFH Stadium,False,a2c14d49-cd7f-4969-bf00-bb6da63e33af
8,614b7046f8090ec74528642d,Regional 1,Fall,Oceania,https://octane.gg/events/642d-rlcs-2021-22-fal...,2021-10-07 23:00:00+00:00,2021-10-17 22:30:00+00:00,Qualifier,Invitational Qualifier,0.0,...,False,False,616150ae143c37878b238867,3.0,2021-10-08 06:23:00+00:00,462.0,stadium_p,DFH Stadium,True,16266154-7a8f-43e8-9685-c29735861f42
9,614b7046f8090ec74528642d,Regional 1,Fall,Oceania,https://octane.gg/events/642d-rlcs-2021-22-fal...,2021-10-07 23:00:00+00:00,2021-10-17 22:30:00+00:00,Qualifier,Invitational Qualifier,0.0,...,False,False,616150b3f8090ec745287113,4.0,2021-10-08 06:29:44+00:00,300.0,stadium_p,DFH Stadium,False,08de2364-775f-4bb8-bbe1-446eeea83517

In [21]:
df_match_players.info()
df_match_players.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26176 entries, 0 to 26175
Data columns (total 90 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   match_id                                        26176 non-null  object
 1   team_id                                         26176 non-null  object
 2   team_region                                     26155 non-null  object
 3   player_id                                       26176 non-null  object
 4   player_tag                                      26176 non-null  object
 5   core_shots                                      26176 non-null  float64
 6   core_goals                                      26176 non-null  float64
 7   core_saves                                      26176 non-null  float64
 8   core_assists                                    26176 non-null  float64
 9   core_score                                      26176 non-null  float64
 10  core_shooting_percentage                        26176 non-null  float64
 11  boost_bpm                                       26036 non-null  float64
 12  boost_bcpm                                      26036 non-null  float64
 13  boost_avg_amount                                26036 non-null  float64
 14  boost_amount_collected                          26036 non-null  float64
 15  boost_amount_stolen                             26036 non-null  float64
 16  boost_amount_collected_big                      26036 non-null  float64
 17  boost_amount_stolen_big                         26036 non-null  float64
 18  boost_amount_collected_small                    26036 non-null  float64
 19  boost_amount_stolen_small                       26036 non-null  float64
 20  boost_count_collected_big                       26036 non-null  float64
 21  boost_count_stolen_big                          26036 non-null  float64
 22  boost_count_collected_small                     26036 non-null  float64
 23  boost_count_stolen_small                        26036 non-null  float64
 24  boost_amount_overfill                           26036 non-null  float64
 25  boost_amount_overfill_stolen                    26036 non-null  float64
 26  boost_amount_used_while_supersonic              26036 non-null  float64
 27  boost_time_zero_boost                           26036 non-null  float64
 28  boost_percent_zero_boost                        26036 non-null  float64
 29  boost_time_full_boost                           26036 non-null  float64
 30  boost_percent_full_boost                        26036 non-null  float64
 31  boost_time_boost_0_25                           26036 non-null  float64
 32  boost_time_boost_25_50                          26036 non-null  float64
 33  boost_time_boost_50_75                          26036 non-null  float64
 34  boost_time_boost_75_100                         26036 non-null  float64
 35  boost_percent_boost_0_25                        26036 non-null  float64
 36  boost_percent_boost_25_50                       26036 non-null  float64
 37  boost_percent_boost_50_75                       26036 non-null  float64
 38  boost_percent_boost_75_100                      26036 non-null  float64
 39  movement_avg_speed                              26036 non-null  float64
 40  movement_total_distance                         26036 non-null  float64
 41  movement_time_supersonic_speed                  26036 non-null  float64
 42  movement_time_boost_speed                       26036 non-null  float64
 43  movement_time_slow_speed                        26036 non-null  float64
 44  movement_time_ground                            26036 non-null  float64
 45  movement_time_low_air                           26036 non-null  float64
 46  movement_time_high_air                          26036 non-null  float64
 47  movement_time_powerslide                        26036 non-null  float64
 48  movement_count_powerslide                       26036 non-null  float64
 49  movement_avg_powerslide_duration                26036 non-null  float64
 50  movement_avg_speed_percentage                   26036 non-null  float64
 51  movement_percent_slow_speed                     26036 non-null  float64
 52  movement_percent_boost_speed                    26036 non-null  float64
 53  movement_percent_supersonic_speed               26036 non-null  float64
 54  movement_percent_ground                         26036 non-null  float64
 55  movement_percent_low_air                        26036 non-null  float64
 56  movement_percent_high_air                       26036 non-null  float64
 57  positioning_avg_distance_to_ball                26036 non-null  float64
 58  positioning_avg_distance_to_ball_possession     26036 non-null  float64
 59  positioning_avg_distance_to_ball_no_possession  26036 non-null  float64
 60  positioning_avg_distance_to_mates               26036 non-null  float64
 61  positioning_time_defensive_third                26036 non-null  float64
 62  positioning_time_neutral_third                  26036 non-null  float64
 63  positioning_time_offensive_third                26036 non-null  float64
 64  positioning_time_defensive_half                 26036 non-null  float64
 65  positioning_time_offensive_half                 26036 non-null  float64
 66  positioning_time_behind_ball                    26036 non-null  float64
 67  positioning_time_in_front_ball                  26036 non-null  float64
 68  positioning_time_most_back                      26036 non-null  float64
 69  positioning_time_most_forward                   26036 non-null  float64
 70  positioning_goals_against_while_last_defender   26036 non-null  float64
 71  positioning_time_closest_to_ball                26036 non-null  float64
 72  positioning_time_farthest_from_ball             26036 non-null  float64
 73  positioning_percent_defensive_third             26036 non-null  float64
 74  positioning_percent_offensive_third             26036 non-null  float64
 75  positioning_percent_neutral_third               26036 non-null  float64
 76  positioning_percent_defensive_half              26036 non-null  float64
 77  positioning_percent_offensive_half              26036 non-null  float64
 78  positioning_percent_behind_ball                 26036 non-null  float64
 79  positioning_percent_in_front_ball               26036 non-null  float64
 80  positioning_percent_most_back                   26036 non-null  float64
 81  positioning_percent_most_forward                26036 non-null  float64
 82  positioning_percent_closest_to_ball             26036 non-null  float64
 83  positioning_percent_farthest_from_ball          26036 non-null  float64
 84  demo_inflicted                                  26036 non-null  float64
 85  demo_taken                                      26036 non-null  float64
 86  advanced_goal_participation                     26176 non-null  float64
 87  advanced_rating                                 26176 non-null  float64
 88  score                                           26176 non-null  float64
 89  winner                                          26176 non-null  bool
dtypes: bool(1), float64(84), object(5)
memory usage: 17.8+ MB

,match_id,team_id,team_region,player_id,player_tag,core_shots,core_goals,core_saves,core_assists,core_score,...,positioning_percent_most_back,positioning_percent_most_forward,positioning_percent_closest_to_ball,positioning_percent_farthest_from_ball,demo_inflicted,demo_taken,advanced_goal_participation,advanced_rating,score,winner
0,6159ad3d143c37878b2384a9,6020bc8ef1e4807cc700391a,Oceania,5f3d8fdd95f40596eae2412e,Amphis,9.0,3.0,4.0,0.0,1119.0,...,36.110946,32.808284,32.244507,35.198802,2.0,2.0,33.333333,0.863590,3.0,True
1,6159ad3d143c37878b2384a9,6020bc8ef1e4807cc700391a,Oceania,5f3d8fdd95f40596eae23e01,Torsos,13.0,2.0,2.0,5.0,1209.0,...,30.298075,35.344441,37.177801,32.454502,2.0,0.0,77.777778,1.350500,3.0,True
2,6159ad3d143c37878b2384a9,6020bc8ef1e4807cc700391a,Oceania,5f3d8fdd95f40596eae23e53,Express,12.0,4.0,2.0,2.0,1077.0,...,35.348030,32.218735,30.874362,34.141855,2.0,5.0,66.666667,1.232970,3.0,True
3,6159ad3d143c37878b2384a9,614c8930f8090ec745286474,Oceania,5f7ca648ea8a0f0714fb9a20,Laxin,5.0,1.0,8.0,1.0,1086.0,...,33.660595,35.306617,33.799467,36.263424,1.0,2.0,40.000000,0.806692,0.0,False
4,6159ad3d143c37878b2384a9,614c8930f8090ec745286474,Oceania,5f3d8fdd95f40596eae24503,Baked Potato,4.0,3.0,4.0,0.0,948.0,...,29.400720,35.309532,35.846261,27.821551,3.0,3.0,60.000000,1.077983,0.0,False
5,6159ad3d143c37878b2384a9,614c8930f8090ec745286474,Oceania,604e562901d675f81a96b270,mel kin,6.0,1.0,9.0,2.0,1105.0,...,38.306270,29.683878,30.390490,37.262072,3.0,1.0,60.000000,0.987119,0.0,False
6,6159ad3d143c37878b2384aa,6020bc70f1e4807cc70023fb,Oceania,5f3d8fdd95f40596eae24077,Fever,13.0,5.0,6.0,9.0,1971.0,...,40.036218,27.155715,36.237765,30.214015,5.0,1.0,66.666667,2.248582,3.0,True
7,6159ad3d143c37878b2384aa,6020bc70f1e4807cc70023fb,Oceania,5f3d8fdd95f40596eae23e36,Kamii,14.0,4.0,3.0,6.0,1381.0,...,34.576086,28.605074,30.405308,35.777341,3.0,1.0,47.619048,1.619979,3.0,True
8,6159ad3d143c37878b2384aa,6020bc70f1e4807cc70023fb,Oceania,5f3d8fdd95f40596eae23e59,CJCJ,19.0,12.0,1.0,6.0,2319.0,...,25.358094,42.932479,32.031975,33.997749,3.0,5.0,85.714286,2.648211,3.0,True
9,6159ad3d143c37878b2384aa,6156d4db143c37878b238367,Oceania,5f5ae860c6cbf591c568a505,Viic,7.0,1.0,4.0,2.0,956.0,...,32.753691,30.416451,33.837268,30.699959,4.0,4.0,75.000000,0.803442,0.0,False

In [22]:
df_match_team.info()
df_match_team.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10594 entries, 0 to 10593
Data columns (total 54 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   match_id                            10594 non-null  object
 1   color                               10594 non-null  object
 2   team_id                             10594 non-null  object
 3   team_slug                           10594 non-null  object
 4   team_name                           10594 non-null  object
 5   team_region                         10587 non-null  object
 6   core_shots                          8708 non-null   float64
 7   core_goals                          8708 non-null   float64
 8   core_saves                          8708 non-null   float64
 9   core_assists                        8708 non-null   float64
 10  core_score                          8708 non-null   float64
 11  core_shooting_percentage            8708 non-null   float64
 12  boost_bpm                           8662 non-null   float64
 13  boost_bcpm                          8662 non-null   float64
 14  boost_avg_amount                    8662 non-null   float64
 15  boost_amount_collected              8662 non-null   float64
 16  boost_amount_stolen                 8662 non-null   float64
 17  boost_amount_collected_big          8662 non-null   float64
 18  boost_amount_stolen_big             8662 non-null   float64
 19  boost_amount_collected_small        8662 non-null   float64
 20  boost_amount_stolen_small           8662 non-null   float64
 21  boost_count_collected_big           8662 non-null   float64
 22  boost_count_stolen_big              8662 non-null   float64
 23  boost_count_collected_small         8662 non-null   float64
 24  boost_count_stolen_small            8662 non-null   float64
 25  boost_amount_overfill               8662 non-null   float64
 26  boost_amount_overfill_stolen        8662 non-null   float64
 27  boost_amount_used_while_supersonic  8662 non-null   float64
 28  boost_time_zero_boost               8662 non-null   float64
 29  boost_time_full_boost               8662 non-null   float64
 30  boost_time_boost_0_25               8662 non-null   float64
 31  boost_time_boost_25_50              8662 non-null   float64
 32  boost_time_boost_50_75              8662 non-null   float64
 33  boost_time_boost_75_100             8662 non-null   float64
 34  movement_total_distance             8662 non-null   float64
 35  movement_time_supersonic_speed      8662 non-null   float64
 36  movement_time_boost_speed           8662 non-null   float64
 37  movement_time_slow_speed            8662 non-null   float64
 38  movement_time_ground                8662 non-null   float64
 39  movement_time_low_air               8662 non-null   float64
 40  movement_time_high_air              8662 non-null   float64
 41  movement_time_powerslide            8662 non-null   float64
 42  movement_count_powerslide           8662 non-null   float64
 43  positioning_time_defensive_third    8662 non-null   float64
 44  positioning_time_neutral_third      8662 non-null   float64
 45  positioning_time_offensive_third    8662 non-null   float64
 46  positioning_time_defensive_half     8662 non-null   float64
 47  positioning_time_offensive_half     8662 non-null   float64
 48  positioning_time_behind_ball        8662 non-null   float64
 49  positioning_time_in_front_ball      8662 non-null   float64
 50  demo_inflicted                      8662 non-null   float64
 51  demo_taken                          8662 non-null   float64
 52  score                               10594 non-null  float64
 53  winner                              10594 non-null  bool
dtypes: bool(1), float64(47), object(6)
memory usage: 4.3+ MB

,match_id,color,team_id,team_slug,team_name,team_region,core_shots,core_goals,core_saves,core_assists,...,positioning_time_neutral_third,positioning_time_offensive_third,positioning_time_defensive_half,positioning_time_offensive_half,positioning_time_behind_ball,positioning_time_in_front_ball,demo_inflicted,demo_taken,score,winner
0,6159ad3d143c37878b2384a9,blue,6020bc8ef1e4807cc700391a,https://octane.gg/teams/391a-ground-zero-gaming,GROUND ZERO GAMING,Oceania,34.0,9.0,8.0,7.0,...,973.23,733.45,1967.99,1237.05,2339.78,865.27,6.0,7.0,3.0,True
1,6159ad3d143c37878b2384a9,orange,614c8930f8090ec745286474,https://octane.gg/teams/6474-ranga-roundup,RANGA ROUNDUP,Oceania,15.0,5.0,21.0,3.0,...,1060.71,526.78,2209.56,998.99,2318.26,890.30,7.0,6.0,0.0,False
2,6159ad3d143c37878b2384aa,blue,6020bc70f1e4807cc70023fb,https://octane.gg/teams/23fb-renegades,RENEGADES,Oceania,46.0,21.0,10.0,21.0,...,1247.16,892.76,1972.65,1505.61,2616.06,862.25,11.0,7.0,3.0,True
3,6159ad3d143c37878b2384aa,orange,6156d4db143c37878b238367,https://octane.gg/teams/8367-trident-esports,TRIDENT ESPORTS,Oceania,16.0,4.0,16.0,3.0,...,1001.96,434.29,2600.17,859.84,2355.02,1105.02,7.0,11.0,0.0,False
4,6159ad3d143c37878b2384ab,blue,6020bc8ef1e4807cc7003915,https://octane.gg/teams/3915-dire-wolves,DIRE WOLVES,Oceania,46.0,12.0,13.0,9.0,...,1586.90,998.94,2900.66,1718.97,3444.64,1174.96,13.0,8.0,3.0,True
5,6159ad3d143c37878b2384ab,orange,6091ad1bd50a7d046663343d,https://octane.gg/teams/343d-team-eros,TEAM EROS,Oceania,24.0,6.0,23.0,4.0,...,1502.40,669.61,3308.31,1290.61,3262.44,1336.52,8.0,13.0,1.0,False
6,6159ad3d143c37878b2384ac,blue,615332c4143c37878b237fa6,https://octane.gg/teams/7fa6-wildcard-gaming,WILDCARD GAMING,Oceania,46.0,19.0,10.0,14.0,...,1125.59,734.61,2139.57,1269.87,2510.95,898.50,8.0,11.0,3.0,True
7,6159ad3d143c37878b2384ac,orange,604e562301d675f81a96aea6,https://octane.gg/teams/aea6-big-goose,BIG GOOSE,Oceania,18.0,6.0,21.0,5.0,...,1042.83,616.54,2309.80,1104.88,2400.63,1014.12,11.0,8.0,0.0,False
8,6159ad3d143c37878b2384ad,blue,6020bec4f1e4807cc70163fc,https://octane.gg/teams/63fc-r-ot-gaming,R!OT GAMING,Oceania,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,True
9,6159ad3d143c37878b2384ad,orange,60c1e2879fc1a47e5f1116c8,https://octane.gg/teams/16c8-panik-gaming,PANIK GAMING,Oceania,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,False

In [23]:
df_players.info()
df_players.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1218 entries, 0 to 1217
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   player_id       1218 non-null   object
 1   player_slug     1218 non-null   object
 2   player_tag      1218 non-null   object
 3   player_name     511 non-null    object
 4   player_country  1216 non-null   object
dtypes: object(5)
memory usage: 47.7+ KB

,player_id,player_slug,player_tag,player_name,player_country
0,6284d6ccc437fde7e02d6e7b,https://octane.gg/players/6e7b-yasudon,*YASUDON*,NaN,jp
1,60c46a3a9fc1a47e5f11199a,https://octane.gg/players/199a-2die4,2Die4,David Morgenrood,za
2,5f3d8fdd95f40596eae241b7,https://octane.gg/players/41b7-2piece,2Piece,Jayden Horton,us
3,61daef8bda9d7ca1c7ba3d33,https://octane.gg/players/3d33-3mari,3mari,NaN,sa
4,62712944da9d7ca1c7badbfa,https://octane.gg/players/dbfa-47_vt,47_VT,NaN,jp
5,61fe4a56da9d7ca1c7ba7bd4,https://octane.gg/players/7bd4-5bs,5bs,NaN,za
6,61ed28c5da9d7ca1c7ba5b2e,https://octane.gg/players/5b2e-683h,683h,NaN,sa
7,621ca644c437fde7e02d0fec,https://octane.gg/players/0fec-a8ch,A8CH,NaN,za
8,61800fd0f8090ec74528a5f4,https://octane.gg/players/a5f4-a_clever_rabbit,a_clever_rabbit,NaN,za
9,617d200ef8090ec745289fdf,https://octane.gg/players/9fdf-abdelaty,Abdelaty,NaN,eg